/*
  Annotation of clusters generated by attract / kegg  
*/

create temp table annotation AS(
    -- Annotation from C. Tuggle (probe -> gene_name) where gene_names have associated ensembl_gene_id
    select annotation_ctuggle.probe_set_id, annotation_ctuggle.gene_name, annotation_ctuggle_ensembl.ensembl_gene_id
    from annotation_ctuggle inner join annotation_ctuggle_ensembl on
    annotation_ctuggle.gene_name = annotation_ctuggle_ensembl.gene_name
);

/*                         Using KEGG pathways clusters                        */

-- Clusters to show in table (same as those plotted)
drop table if exists kegg_pway;
create temp table kegg_pway AS(
    select * from attract_ranked_pathways where pathway in 
        ('Antigen processing and presentation', 'Cell adhesion molecules (CAMs)', 'Chemokine signaling pathway',
         'Cytokine-cytokine receptor interaction', 'Endocytosis', 'Lysosome',
         'MAPK signaling pathway', 'NOD-like receptor signaling pathway', 'Phagosome',
         'RIG-I-like receptor signaling pathway', 'TGF-beta signaling pathway', 'Toll-like receptor signaling pathway')
);

-- Annotation from C. Tuggle.
drop table if exists kegg_genes;
create temp table kegg_genes AS(
select distinct kegg_pway.pathway, attract_synexpr_groups_kegg.cluster_group, annotation.gene_name
from attract_synexpr_groups_kegg inner join kegg_pway on 
  attract_synexpr_groups_kegg.keggid = kegg_pway.keggid
  inner join annotation on 
  attract_synexpr_groups_kegg.probe_set_id = annotation.probe_set_id
  -- Optionally, restrict to probes mapped to kegg pathways:
where attract_synexpr_groups_kegg.kegg_probe = 1
order by pathway, cluster_group, annotation.gene_name
);

select * from kegg_genes;

-- Genes in ambigous positions (present in more than one cluster within the same pathway)
select count(*) as no_ambig, pathway, gene_name from kegg_genes group by pathway, gene_name having count(*) > 1 ;

/*                             All probes clustered                          */

drop table cluster_genes;
create temp table cluster_genes AS(
  select distinct attract_synexpr_groups.cluster_group, count(distinct gene_name) AS size, sort_distinct(array_agg(annotation.gene_name)) as gene_names, sort_distinct(array_agg(annotation.ensembl_gene_id))
  from attract_synexpr_groups inner join annotation on 
     attract_synexpr_groups.probe_set_id= annotation.probe_set_id
  where kegg_probe = 1 and
    -- Get only clusters of interest (top five in big multiplot)
    cluster_group in('12', '1', '25', '17', '6')
  group by cluster_group
  order by cluster_group
);

select distinct kegg_pway.pathway, attract_synexpr_groups.cluster_group, annotation.gene_name
from attract_synexpr_groups inner join kegg_pway on 
  attract_synexpr_groups.keggid = kegg_pway.keggid
  inner join annotation on 
  attract_synexpr_groups.probe_set_id = annotation.probe_set_id
  -- Optionally, restrict to probes mapped to kegg pathways:
where attract_synexpr_groups.kegg_probe = 1
order by pathway, cluster_group, annotation.gene_name;

/* Cluster expression: What is connected with what */
select cross_tab($$
  select attract_ranked_pathways.pathway || '_' || attract_synexpr_groups_kegg.cluster_group AS cluster_id, 'tp' || lpad(time_point::text, 2, '0') as time_point, avg(log2_intensity) as expression
  from attract_synexpr_groups_kegg inner join attract_ranked_pathways
     on attract_ranked_pathways.keggid = attract_synexpr_groups_kegg.keggid
     inner join affyarray_bmdm_avg on
       affyarray_bmdm_avg.probe_set_id = attract_synexpr_groups_kegg.probe_set_id
  where pathway in 
        ('Antigen processing and presentation', 'Cell adhesion molecules (CAMs)', 'Chemokine signaling pathway',
         'Cytokine-cytokine receptor interaction', 'Endocytosis', 'Lysosome',
         'MAPK signaling pathway', 'NOD-like receptor signaling pathway', 'Phagosome',
         'RIG-I-like receptor signaling pathway', 'TGF-beta signaling pathway', 'Toll-like receptor signaling pathway')
  group by attract_ranked_pathways.pathway || '_' || attract_synexpr_groups_kegg.cluster_group, time_point
  order by attract_ranked_pathways.pathway || '_' || attract_synexpr_groups_kegg.cluster_group, time_point
$$, 'tmp_clusters_kegg_ct');
copy tmp_clusters_kegg_ct to 'D:/Tritume/kegg_cluster.expression' with csv delimiter E'\t' header;
drop table tmp_clusters_kegg_ct;

-------------------------------------------------------------------------------
-- TRITUME
-------------------------------------------------------------------------------
select  attract_synexpr_groups_kegg.* 
from attract_synexpr_groups_kegg inner join attract_ranked_pathways on attract_ranked_pathways.keggid = attract_synexpr_groups_kegg.keggid
where attract_synexpr_groups_kegg.keggid = '04010'
order by attract_synexpr_groups_kegg.keggid, cluster_group, kegg_probe desc;

select count(*), count(distinct probe_set_id) from attract_synexpr_groups where kegg_probe = 0;



select pathway, cluster_group, count(*) AS no_genes, array_agg(gene_name) AS gene_names
from kegg_genes
group by pathway, cluster_group
order by pathway, cluster_group;


select * from attract_synexpr_groups where cluster_group = '12'
select * from attract_synexpr_groups where cluster_group = '1'
select * from attract_synexpr_groups where cluster_group = '25'
