-- Ewes pregnent with twins (n= 95):
select "Dam", count(distinct "LambID") from "LifeHistory" group by "Dam" having count(*) > 1;

-- Lambs without adult worms at PM (n= 37):
select * from "cBlackF" where "Control" is False and "AdTot" > 0;

select "Dam", count(distinct "LambID") from "LifeHistory" group by "Dam";


-- Cross tab table of tag counts (excluding the library that 'failed')
select cross_tab($$ select "TagChrPos", "LibraryID", "CumCount" from "outSolexaCumCount"$$, 'out_crosstab_cumcount');
alter table out_crosstab_cumcount set schema "Blackface_Solexa";
comment on table out_crosstab_cumcount IS $comment$ This table generated by: select cross_tab($$ select "TagChrPos", "LibraryID", "CumCount" from "outSolexaCumCount"$$, 'out_crosstab_cumcount') $comment$

-- Genome position mapped by each library:
select "LibraryID", count(*) AS no_positions from "outSolexaCumCount" group by "LibraryID" order by no_positions;
