#!/usr/bin/env Rscript

VERSION<- '0.2.0'

## Load packages
## =============
done<- suppressWarnings(suppressMessages(require(ggplot2)))
if(done == FALSE){
    cat('\nPlease install the "ggplot2" package. Open an R session and execute:\n\n')
    cat('> install.packages("ggplot2")\n\n')
    quit(save= 'no', status= 1)
}

# ==============================================================================

printHelp<- function(opts, subcommand= NULL){
    ## opts: List of arguments for which hep should be printed
    ## subcommand: Print help for this subcommand group
    if(is.null(subcommand)){
        cat(opts$description)
        cat('\nPLOT TYPES:\n')
        for(x in names(opts$subcommands)){
            cat(sprintf('%s\n    %s\n', x, opts$subcommand[[x]]))
        }
    } else {
        cat(subcommand, ' ', opts$subcommands[[subcommand]], '\n')
        for(x in names(opts$options)){
            if(subcommand %in% opts$options[[x]]$subcommand){
                cat(sprintf('-%s\n    %s\n', x, opts$options[[x]]$help))
            }
        }
    }
}

getArgFromCmdLine<- function(opt, cmdArgs, nargs= 1){
    # opt: Option to fetch from command line, w/o leading -
    # cmdArgs: Vector of commands arguments collected from commandArgs()
    # Return the values associated with opt or NA if opt is not found
    xarg<- NA
    cmdArg<- paste0('-', opt)
    if(cmdArg %in% cmdArgs){
        xarg<- cmdArgs[which(cmdArgs == cmdArg) + nargs]
    }
    return(xarg)
}

parseOptions<- function(opts, cmdArgs= NULL){
    ## Parse options to comply with data type
    xargs<- list()
    for(opt in names(opts$options)){
        x<- opts$options[[opt]]
        xarg<- getArgFromCmdLine(opt, cmdArgs)
        if(is.na(xarg)){
            xarg<- x$arg
        }
        if(x$type == 'pos_num'){
            n<- suppressWarnings(as.numeric(xarg))
            if(is.na(n) || n <= 0){
                cat('Invalid argument: ', xarg, ' to option -', opt, '\n', sep= '')
                quit()
            } else {
                xarg<- n
            }
        }
        if(x$type == 'numeric'){
            n<- suppressWarnings(as.numeric(xarg))
            if(is.na(n)){
                cat('Invalid argument: ', xarg, ' to option -', opt, '\n', sep= '')
                quit()
            } else {
                xarg<- n
            }
        }
        xargs[[opt]]<- xarg
    }
    return(xargs)
}

guessEOL<- function(buf){
    ## Guess EOL in string by setting EOL to the most frequent
    ## occurence of one of the candidate EOLs.
    x<- substr(buf, 1, 1000000)
    ll<- nchar(x)
    eols<- list('\n'= 0, '\r'= 0, '\r\n'= 0)
    for(n in names(eols)){
        ss<- gsub(n, "", x, fixed= TRUE, useBytes = TRUE)
        numOcc<- ll - nchar(ss)
        eols[[n]]<- numOcc
    }
    eol<- which.max(eols)
    return(names(eol))
}

readLines2<- function(con) {
    ## Faster version of readLines from http://www.r-bloggers.com/faster-files-in-r/
    ## Reading from stdin is much slower!
    if(con != '-'){
        s<- file.info(con)$size
        buf<- readChar(con, s, useBytes=TRUE)
        eol<- guessEOL(buf)
        dat<- strsplit(buf, eol, fixed= TRUE, useBytes= TRUE)[[1]]
    } else {
        fin<- file('stdin', open= 'rb')
        dat<- readLines(fin)
        close(fin)
    }
    return(dat)
}

columnSelector<- function(dat, select){
    # Returns the column indexes corresponding to names in vector `select`
    # along with the row number where the names are first found.
    # dat:
    #   List of vectors
    hdrSel<- list(row= NA, idxs= NA)
    if(!any(is.na(suppressWarnings(as.numeric(select))))){
        hdrSel$row<- 1
        hdrSel$idxs<- as.numeric(select)
        return(hdrSel)
    } else {
        for(i in 1:length(dat)){
            if(all(select %in% dat[[i]])){ # Does this row contain all the colnames?
                hdrSel$row<- i+1
                hdrSel$idxs<- match(select, dat[[i]]) # Indexes of colnames
                return(hdrSel)
            }
        }
        cat(sprintf('Required column name(s) not found: %s\n', paste(select, collapse= ', ')))
        quit(status= 1)
    }
}

reader<- function(con, select, sep){
    # Return dataframe ready to be passed to plotting funcs
    # con:
    #   File connection to read from
    # select:
    #   Vector, if *numeric* column indexes to select. If *character*
    #   name of columns.
    # sep:
    #   Char or string separating columns
    dat<- readLines2(con)
    dat<- strsplit(dat, sep, perl= TRUE, useBytes= TRUE)
    ## If first elements are always empty, drop the first column
    xfirst<- sapply(dat, function (x) x[1])
    if(length(unique(xfirst)) == 1 && unique(xfirst) == ""){
        dat<- lapply(dat, function (x) x[2:length(x)]) 
    }
    hdrSel<- columnSelector(dat, select)
    dat<- dat[hdrSel$row:length(dat)]
    dat<- lapply(dat, function(x) x[hdrSel$idxs])
    dat<- do.call('rbind', dat)
    return(data.frame(dat, stringsAsFactors= FALSE))
}

winsor2<- function (x, multiple=3){
    ## From http://www.r-bloggers.com/winsorization/
   if(length(multiple) != 1 || multiple <= 0) {
      stop("bad value for 'multiple'")
   }
   med <- median(x)
   y <- x - med
   sc <- mad(y, center=0) * multiple
   y[ y > sc ] <- sc
   y[ y < -sc ] <- -sc
   y + med
}

correctForLog<- function(x, add_pct= 0.01){
    # Prepare data vector x to be log-transformed
    # If all the values in x are > 0 then do nothing otherwise 
    # if zeros are present, add a pseudo-increment 
    # pct_add: Increment based on this % of the smalles value
    # ...
}

getTitle<- function(N, xtitle){
    # Prepare ggtitle object
    # N: Integer giving the number of datapoints
    # xtitle: String for the title
    N_title<- sprintf('N: %s', N)
    if(xargs$title != ''){
        xtitle<- ggtitle(sprintf('%s\n%s', xargs$title, N_title))
        # xtitle<- ggtitle(bquote(atop(.(sprintf(xargs$title)), atop(italic(.(N_title)), ""))))
    } else {
        xtitle<- ggtitle(N_title)
    }
    return(xtitle)
}

noNumericData<- function(dat= NULL){
    # Function to print and exit if no numeric data is found
    # dat:
    #     object to show to help finding out why no numeric data
    
    #print(head(dat))
    cat("No numeric data found!\n")
    quit()
}


## =============================================================================
## Initialize options
## =============================================================================
MAIN_HELP= sprintf('DESCRIPTION
Lightweight inline plotter. Version %s.

USAGE
    plot <plot-type> <args to plot-type>

HELP
    plot <plot-type> -h
    ', VERSION)

opts<- list(
    description= MAIN_HELP,
    subcommands= list(
        histogram= "Histogram of numeric x values",
        xyplot= "Scatter plot of numeric x and y values",
        boxplot= "Box or violin plot of numeric y values in x categories",
        barplot= "Barplot of numeric y values in x categories"),
    options= list(
        i= list(arg= '-', help= 'Input file. Use - to read from stdin', subcommand= c('histogram', 'xyplot', 'boxplot', 'barplot'), type= 'string'),
        d= list(arg= '\\s+', help= 'Column delimiter interpreted as regex. Default splits at one or more tab or space: \\s+', subcommand= c('histogram', 'xyplot', 'boxplot', 'barplot'), type= 'string'),
        x= list(arg= 1, help= 'Column name or index for x values to plot. Default 1', subcommand= c('histogram', 'xyplot', 'boxplot', 'barplot'), type= 'string'),
        y= list(arg= 2, help= 'Column name or index for y values to plot. Default 2', subcommand= c('xyplot', 'boxplot', 'barplot'), type= 'string'),
        b= list(arg= 30, help= 'Number of bins', subcommand= 'histogram', type= 'pos_num'),
        log= list(arg= 'na', help= 'Set axes in log10 scale. Options: "x", "y", "xy"', subcommand= c('xyplot', 'boxplot', 'barplot', 'histogram'), type= 'string'),
        flip= list(arg= 'F', help= 'T: Flip coordinates', subcommand= c('boxplot', 'barplot'), type= 'string'),
        t= list(arg= 'p', help= 'Type of geom to plot. "p": point (default), "l": line,
    "smooth": smooth scatter plot', subcommand= 'xyplot', type= 'string'),
        xwin= list(arg= -1,
            help= 'Reset outliers in X by winsorizing data beyond this multiple of the median.
    2 or 3 is usually good choice. Set to <= 0 to disable', subcommand= c('histogram', 'xyplot'), type= 'numeric'),
        ywin= list(arg= -1,
            help= 'Reset outliers in Y by winsorizing data beyond this multiple of the median.
    2 or 3 is usually good choice. Set to <= 0 to disable', subcommand= c('boxplot', 'xyplot', 'barplot'), type= 'numeric'),
        bty= list(arg= 'box', help= 'Boxplot type. Options: "box" default boxplot, "varwidth" boxes with width proportional to n obs,
    "notch" nocthed boxplot, "violin" violin plot', subcommand= 'boxplot', type= 'string'),
        s= list(arg= 1, help= 'Size of the point or line', subcommand= 'xyplot', type= 'numeric'),
        a= list(arg= 1, help= 'Alpha transparency [0, 1] (NB: Not always supported)', subcommand= 'xyplot', type= 'numeric'),
        S= list(arg= 'T', help= 'F: to suppress smooth trendline', subcommand= 'xyplot', type= 'string'),
        title= list(arg= '', help= 'Plot title', subcommand= c('histogram', 'xyplot', 'boxplot', 'barplot'), type= 'string'),
        xlab= list(arg= '', help= 'Label for x-axis', subcommand= c('histogram', 'xyplot', 'boxplot', 'barplot'), type= 'string'),
        ylab= list(arg= '', help= 'Label for y-axis', subcommand= c('histogram', 'xyplot', 'boxplot', 'barplot'), type= 'string'),
        o= list(arg= '-', help= 'Output file. Default is to plot to x11 window', subcommand= c('histogram', 'xyplot', 'boxplot', 'barplot'), type= 'string'),
        w= list(arg= 14, help= 'Width in cm of output window', subcommand= c('histogram', 'xyplot', 'boxplot', 'barplot'), type= 'pos_num'),
        h= list(arg= 14, help= 'Height in cm of output window', subcommand= c('histogram', 'xyplot', 'boxplot', 'barplot'), type= 'pos_num')
        )
)
## =============================================================================
## Parse arguments
## =============================================================================
cmdArgs<- commandArgs(trailingOnly= TRUE)
if(length(cmdArgs) == 0 || cmdArgs[1] == '-h'){
    printHelp(opts)
    quit()
}

subcmd<- cmdArgs[1]
tryCatch({
    subcmd<- match.arg(subcmd, names(opts$subcommand))
}, error = function(x) {
    cat(sprintf("\nInvalid plot option: %s. Options are: %s\n\n", subcmd, paste(names(opts$subcommand), collapse= ', ')))
    quit()
})

subcmdOpts<- cmdArgs[2:length(options)]
if('-h' %in% subcmdOpts){
    printHelp(opts, subcmd)
    quit()
}
xargs<- parseOptions(opts, cmdArgs)

## Plot data
## =========
axisTextX<- theme(axis.text.x= element_text(angle= 90, hjust= 1, vjust= 0.5))

if(subcmd == 'histogram'){

    dat<- reader(xargs$i, sep= xargs$d, select= c(xargs$x))
    xdat<- suppressWarnings(as.numeric(dat[, 1]))
    xdat<- xdat[!is.na(xdat)]
    if(length(xdat) == 0) {
         noNumericData()
    }
    if(xargs$xwin > 0){
        xdat<- winsor2(xdat, xargs$xwin)
    }
    gg<- ggplot(data= NULL, aes(x= xdat)) +
        geom_histogram(binwidth = (range(xdat)[2] - range(xdat)[1]) / xargs$b, colour= 'white') +
       getTitle(length(xdat), xargs$title)
    
    # X and Y labs
    if(xargs$xlab == '') {gg<- gg + xlab(xargs$x)} else {gg<- gg + xlab(xargs$xlab)}
    if(xargs$ylab != '') {gg<- gg + ylab(xargs$ylab)}
    
    if(xargs$log == "x" || xargs$log == "xy"){
        gg<- gg + scale_x_log10()
    }
    if(xargs$log == "y" || xargs$log == "xy"){
        gg<- gg + scale_y_log10()
    }
}

if(subcmd == 'xyplot'){
    dat<- reader(xargs$i, sep= xargs$d, select= c(xargs$x, xargs$y))
    names(dat)<- c('x', 'y')
    dat$x<- suppressWarnings(as.numeric(dat$x))
    dat$y<- suppressWarnings(as.numeric(dat$y))
    cmp<- complete.cases(dat)
    dat<- dat[cmp, ]
    if(nrow(dat) == 0) {
        noNumericData()
    }
    if(xargs$xwin > 0){
        dat$x<- winsor2(dat$x, xargs$xwin)
    }
    if(xargs$ywin > 0){
        dat$y<- winsor2(dat$y, xargs$ywin)
    }
    gg<- ggplot(data= dat, aes(x= x, y= y)) + 
          getTitle(sum(cmp), xargs$title)
    
    # X and Y labs
    if(xargs$xlab == '') {gg<- gg + xlab(xargs$x)} else {gg<- gg + xlab(xargs$xlab)}
    if(xargs$ylab == '') {gg<- gg + ylab(xargs$y)} else {gg<- gg + ylab(xargs$ylab)}
    
    if(xargs$t == 'p'){
        gg<- gg + geom_point(size= xargs$s, alpha= xargs$a)
    }
    if(xargs$t == 'l'){
        gg<- gg + geom_line(size= xargs$s, alpha= xargs$a)
    }
    if(xargs$t == 'smooth'){
        ## From http://wresch.github.io/2012/11/06/ggplot2-smoothscatter.html
        xdens<- dat$x
        if(xargs$log == "x" || xargs$log == "xy"){
            xdens<- log10(xdens)
        }        
        ydens<- dat$y
        if(xargs$log == "y" || xargs$log == "xy"){
            ydens<- log10(ydens)
        }
        d<- densCols(xdens, ydens, colramp = colorRampPalette(rev(rainbow(10, end = 4/6))))
        gg<- gg + geom_point(aes(x, y, col = d), size = 0.1) +
             scale_color_identity()
    }
    if(xargs$log == "x" || xargs$log == "xy"){
        gg<- gg + scale_x_log10()
    }
    if(xargs$log == "y" || xargs$log == "xy"){
        gg<- gg + scale_y_log10()
    }
    if(xargs$S != 'F'){
        gg<- gg + geom_smooth()
    }
}

if(subcmd == 'boxplot'){
    dat<- reader(xargs$i, sep= xargs$d, select= c(xargs$x, xargs$y))
    names(dat)<- c('x', 'y')
    dat$y<- suppressWarnings(as.numeric(dat$y))
    cmp<- complete.cases(dat)
    dat<- dat[cmp, ]
    if(nrow(dat) == 0) {
        noNumericData()
    }
    if(xargs$ywin > 0){
        dat$y<- winsor2(dat$y, xargs$ywin)
    }
    grpCnt<- table(dat$x)
    gg<- ggplot(data= dat, aes(x= x, y= y)) +
        getTitle(sum(cmp), xargs$title) +
        axisTextX +
        annotate('text', y= rep(Inf, length(grpCnt)), x= names(grpCnt), label= grpCnt, vjust= 1)

    # X and Y labs
    if(xargs$xlab == '') {gg<- gg + xlab(xargs$x)} else {gg<- gg + xlab(xargs$xlab)}
    if(xargs$ylab == '') {gg<- gg + ylab(xargs$y)} else {gg<- gg + ylab(xargs$ylab)}

    if(xargs$bty == 'violin'){
        gg<- gg + geom_violin(fill= 'blue', alpha= 0.5, colour= 'blue') + geom_boxplot(width=.1, alpha= 0.5, outlier.colour= 'transparent')
    } else {
        gg<- gg + geom_boxplot(
            varwidth= ifelse(xargs$bty == 'varwidth', TRUE, FALSE),
            notch= ifelse(xargs$bty == 'notch', TRUE, FALSE))
    }
    if(xargs$log == "y" || xargs$log == "xy"){
        gg<- gg + scale_y_log10()
    } 
    if(xargs$flip == 'T'){
        gg<- gg + coord_flip()
    }
}

if(subcmd == 'barplot'){
    dat<- reader(xargs$i, sep= xargs$d, select= c(xargs$x, xargs$y))
    names(dat)<- c('x', 'y')
    dat$y<- suppressWarnings(as.numeric(dat$y))
    cmp<- complete.cases(dat)
    dat<- dat[cmp, ]
    if(nrow(dat) == 0) {
        noNumericData()
    }
    if(xargs$ywin > 0){
        dat$y<- winsor2(dat$y, xargs$ywin)
    }
    ## FIXME? Multiple x categories are stacked!
    gg<- ggplot(data= dat, aes(x= factor(x, levels= unique(x)), y= y)) +
        getTitle(sum(cmp), xargs$title) +
        geom_bar(stat= 'identity') +
        axisTextX

    # X and Y labs
    if(xargs$xlab == '') {gg<- gg + xlab(xargs$x)} else {gg<- gg + xlab(xargs$xlab)}
    if(xargs$ylab == '') {gg<- gg + ylab(xargs$y)} else {gg<- gg + ylab(xargs$ylab)}

    if(xargs$log == "y" || xargs$log == "xy"){
        gg<- gg + scale_y_log10()
    }
    if(xargs$flip == 'T'){
        gg<- gg + coord_flip()
    }
}


## Report
## ======
if(xargs$o == '-'){
    x11(width= xargs$w/2.54, height= xargs$h/2.54)
    suppressWarnings(print(gg))
    message("Ctrl-C to terminate")
    Sys.sleep(10000000)
} else {
    ggsave(xargs$o, width= xargs$w, height= xargs$h, units= 'cm')
}
quit()
